### ISSUE TITLE
Procsy is not a class (TypeError)

### ISSUE THREAD

**Issue by lacostenycoder** [NoRedInk/rspec-retry#73]
```
ruby -v
ruby 2.1.10p492 (2016-04-01 revision 54464) [x86_64-darwin15.0]
rails -v
Rails 4.0.0
```
Just running `rspec` throws
```
/Users/lacoste/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/rspec-retry-0.4.6/lib/rspec_ext/rspec_ext.rb:10:in `<class:Example>': Procsy is not a class (TypeError)
	from /Users/lacoste/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/rspec-retry-0.4.6/lib/rspec_ext/rspec_ext.rb:3:in `<module:Core>'
	from /Users/lacoste/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/rspec-retry-0.4.6/lib/rspec_ext/rspec_ext.rb:2:in `<module:RSpec>'
	from /Users/lacoste/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/rspec-retry-0.4.6/lib/rspec_ext/rspec_ext.rb:1:in `<top (required)>'
	from /Users/lacoste/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
	from /Users/lacoste/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `block in require'
	from /Users/lacoste/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
	from /Users/lacoste/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
	from /Users/lacoste/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/rspec-retry-0.4.6/lib/rspec/retry.rb:3:in `<top (required)>'
	from /Users/lacoste/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:105:in `require'
	from /Users/lacoste/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:105:in `rescue in block in require'
	from /Users/lacoste/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:82:in `block in require'
	from /Users/lacoste/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
	from /Users/lacoste/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
	from /Users/lacoste/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
	from /Users/lacoste/dev/clients/thoroughcare/config/application.rb:8:in `<top (required)>'
	from /Users/lacoste/dev/clients/thoroughcare/config/environment.rb:2:in `require'
	from /Users/lacoste/dev/clients/thoroughcare/config/environment.rb:2:in `<top (required)>'
	from /Users/lacoste/dev/clients/thoroughcare/spec/spec_helper.rb:3:in `require'
	from /Users/lacoste/dev/clients/thoroughcare/spec/spec_helper.rb:3:in `<top (required)>'
	from /Users/lacoste/dev/clients/thoroughcare/spec/controllers/admin/acp_consultation_controller_spec.rb:1:in `require'
	from /Users/lacoste/dev/clients/thoroughcare/spec/controllers/admin/acp_consultation_controller_spec.rb:1:in `<top (required)>'
	from /Users/lacoste/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `load'
	from /Users/lacoste/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `block in load_spec_files'
	from /Users/lacoste/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `each'
	from /Users/lacoste/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896:in `load_spec_files'
	from /Users/lacoste/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:22:in `run'
	from /Users/lacoste/.rbenv/versions/2.1.10/lib/ruby/gems/2.1.0/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:80:in `run'
```

**Comment by RohanM** [comment]
I encountered this issue also, which I believe is the same as https://github.com/NoRedInk/rspec-retry/issues/53. Downgrading rspec-retry to 0.4.4 solved the problem for me (0.4.5 breaks on rspec 2).

**Comment by michaelglass** [comment]
what versino of rspec are you using, @lacostenycoder?

**Comment by lacostenycoder** [comment]
@michaelglass  2.14.8  but I'm currently not getting this error when running `rspec` in my native  MacOS.  This may have happened inside a vagrant VM but I can't recall at the moment.

**Comment by michaelglass** [comment]
what about what version of rspec?

**Comment by lacostenycoder** [comment]
@michaelglass Updated previous comment above.

**Comment by michaelglass** [comment]
added to readme, thanks https://github.com/NoRedInk/rspec-retry/commit/c0f0f61d0b4d382633d1ba877df0aed168bda288
